---
output: github_document
bibliography: references.bib
---


```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "README-"
)
# Please put your title here to include it in the file below.
Title <- "External Cues and Policy Preferences: Rethinking the Drivers of Policy Positions"
Authors <- "Francisca Castro, Jennifer Oser, Fernando Feitosa & Nir Ginberg"
Year <- "2025"
```

# `r Title`

[Francisca Castro](https://francisca-castro.com/) • ISDC - International Security and Development Center\
[Jennifer Oser](https://www.jenniferoser.com/) • Department of Politics and Government • Ben-Gurion University of the Negev\
[Fernando Feitosa](https://ferfeitosa.github.io/) • School of Government and International Relations • Griffith University\
[Nir Grinberg](https://www.nirg.net/) • Faculty of Computer and Information Science • Ben-Gurion University of the Negev

------------------------------------------------------------------------

## Abstract

At a time when the influence of external cues on opinion formation is gaining attention due to their relevance for preference formation, this research note investigates how external cues from political elites and close friends shape individual policy preferences. Building on prior studies by Barber and Pope [-@barber2018; -@barber2023] regarding Donald Trump’s impact on people’s policy preferences during his 2017-2021 presidency, we examine whether this influence persists soon after Trump’s first presidential tenure concludes in late 2021 through a survey experiment. We also assess the influence of a second external cue that has gained attention due to the growing role of social media in political processes: a close friend, who might also serve as a relevant figure for policy position formation. We find that Trump’s liberal cues shift Republican preferences in a liberal direction, while close friend cues show diverse patterns, including some backlash effects where individuals adopt positions opposite to conservative friend advocacy. These effects vary with individuals’ party identification, political knowledge, and social conformity levels. Individual characteristics moderate political elite influence, while peer influence operates through reactance mechanisms rather than conformity, revealing that social networks shape opinions through more complex pathways than commonly theorized.


------------------------------------------------------------------------

## How to download and replicate

You can download the data for replication [here](https://github.com/frcastrog/erc-paper-policy-preferences/tree/main/data/data-raw). This is the raw data of Cooperative Election Study (CES) for the period November and December 2021.

The script `00-data-prep` contains the code to make the necessary modifications to the original data, which includes recoding, flag creation, and cleanup.

The script `01-replication` contains the code to replicate the figures and tables of both the manuscript and the supplementary information.

## References
